require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PapersController do

  # This should return the minimal set of attributes required to create a valid
  # Paper. As you add validations to Paper, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { title:"Opgavetitel", undertitel:"Undertitel", forfatter:"Fornavn Efternavn", abstrakt:"ABSTRACT mutus nomen dedit cocis", afleveringsaar:"2011", studium:"Biologi"}
  end

  # This returns a pdf-file to simulate an uploaded file
  # should mock 'original_filename'
  def upload_file(filename,mime)
    file = fixture_file_upload(filename,mime)
    file.stub(:original_filename).and_return(filename)
    file
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PapersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

=begin
  describe "GET index" do
    it "assigns all papers as @papers" do
      paper = Paper.create! valid_attributes
      get :index, {}, valid_session
      assigns(:papers).should eq([paper])
    end
  end
=end

  describe "GET show" do
    it "assigns the requested paper as @paper" do
      paper = Paper.create! valid_attributes
      get :show, {:id => paper.to_param}, valid_session
      assigns(:paper).should eq(paper)
    end
  end

  describe "GET new" do
    it "assigns a new paper as @paper" do
      get :new, {}, valid_session
      assigns(:paper).should be_a_new(Paper)
    end
  end

  describe "GET edit" do
    it "assigns the requested paper as @paper" do
      paper = Paper.create! valid_attributes
      get :edit, {:id => paper.to_param}, valid_session
      assigns(:paper).should eq(paper)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Paper" do
      	file = fixture_file_upload("/test.pdf","application/pdf")
        file.stub!(:original_filename).and_return("test.pdf")
        expect {
          post :create, {:paper => valid_attributes, :file_data => file}, valid_session
        }.to change(Paper, :count).by(1)
      end

      it "assigns a newly created paper as @paper" do
        file = fixture_file_upload("/test.pdf","application/pdf")
        file.stub!(:original_filename).and_return("test.pdf")
        post :create, {:paper => valid_attributes, :file_data => file}, valid_session
        assigns(:paper).should be_a(Paper)
        assigns(:paper).should be_persisted
      end
=begin
      it "redirects to the created paper" do
        post :create, {:paper => valid_attributes}, valid_session
        response.should redirect_to(Paper.last)
      end
=end

    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paper as @paper" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paper.any_instance.stub(:save).and_return(false)
        file = fixture_file_upload("/test.pdf","application/pdf")
        file.stub!(:original_filename).and_return("test.pdf")
        post :create, {:paper => {  }, :file_data => file}, valid_session
        assigns(:paper).should be_a_new(Paper)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Paper.any_instance.stub(:save).and_return(false)
        file = fixture_file_upload("/test.pdf","application/pdf")
        file.stub!(:original_filename).and_return("test.pdf")
        post :create, {:paper => {  }, :file_data => file}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paper" do
        paper = Paper.create! valid_attributes
        # Assuming there are no other papers in the database, this
        # specifies that the Paper created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Paper.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => paper.to_param, :paper => { "these" => "params" }}, valid_session
      end

      it "assigns the requested paper as @paper" do
        paper = Paper.create! valid_attributes
        put :update, {:id => paper.to_param, :paper => valid_attributes}, valid_session
        assigns(:paper).should eq(paper)
      end

      it "redirects to the paper" do
        paper = Paper.create! valid_attributes
        put :update, {:id => paper.to_param, :paper => valid_attributes}, valid_session
        response.should redirect_to(paper)
      end
    end

    describe "with invalid params" do
      it "assigns the paper as @paper" do
        paper = Paper.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paper.any_instance.stub(:save).and_return(false)
        put :update, {:id => paper.to_param, :paper => {  }}, valid_session
        assigns(:paper).should eq(paper)
      end

      it "re-renders the 'edit' template" do
        paper = Paper.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Paper.any_instance.stub(:save).and_return(false)
        put :update, {:id => paper.to_param, :paper => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paper" do
      paper = Paper.create! valid_attributes
      expect {
        delete :destroy, {:id => paper.to_param}, valid_session
      }.to change(Paper, :count).by(-1)
    end

    it "redirects to the papers list" do
      paper = Paper.create! valid_attributes
      delete :destroy, {:id => paper.to_param}, valid_session
      response.should redirect_to(papers_url)
    end
  end

end
