require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaperLanguagesController do

  # This should return the minimal set of attributes required to create a valid
  # PaperLanguage. As you add validations to PaperLanguage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaperLanguagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paper_languages as @paper_languages" do
      paper_language = PaperLanguage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paper_languages).should eq([paper_language])
    end
  end

  describe "GET show" do
    it "assigns the requested paper_language as @paper_language" do
      paper_language = PaperLanguage.create! valid_attributes
      get :show, {:id => paper_language.to_param}, valid_session
      assigns(:paper_language).should eq(paper_language)
    end
  end

  describe "GET new" do
    it "assigns a new paper_language as @paper_language" do
      get :new, {}, valid_session
      assigns(:paper_language).should be_a_new(PaperLanguage)
    end
  end

  describe "GET edit" do
    it "assigns the requested paper_language as @paper_language" do
      paper_language = PaperLanguage.create! valid_attributes
      get :edit, {:id => paper_language.to_param}, valid_session
      assigns(:paper_language).should eq(paper_language)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaperLanguage" do
        expect {
          post :create, {:paper_language => valid_attributes}, valid_session
        }.to change(PaperLanguage, :count).by(1)
      end

      it "assigns a newly created paper_language as @paper_language" do
        post :create, {:paper_language => valid_attributes}, valid_session
        assigns(:paper_language).should be_a(PaperLanguage)
        assigns(:paper_language).should be_persisted
      end

      it "redirects to the created paper_language" do
        post :create, {:paper_language => valid_attributes}, valid_session
        response.should redirect_to(PaperLanguage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paper_language as @paper_language" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaperLanguage.any_instance.stub(:save).and_return(false)
        post :create, {:paper_language => { "title" => "invalid value" }}, valid_session
        assigns(:paper_language).should be_a_new(PaperLanguage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaperLanguage.any_instance.stub(:save).and_return(false)
        post :create, {:paper_language => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paper_language" do
        paper_language = PaperLanguage.create! valid_attributes
        # Assuming there are no other paper_languages in the database, this
        # specifies that the PaperLanguage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaperLanguage.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => paper_language.to_param, :paper_language => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested paper_language as @paper_language" do
        paper_language = PaperLanguage.create! valid_attributes
        put :update, {:id => paper_language.to_param, :paper_language => valid_attributes}, valid_session
        assigns(:paper_language).should eq(paper_language)
      end

      it "redirects to the paper_language" do
        paper_language = PaperLanguage.create! valid_attributes
        put :update, {:id => paper_language.to_param, :paper_language => valid_attributes}, valid_session
        response.should redirect_to(paper_language)
      end
    end

    describe "with invalid params" do
      it "assigns the paper_language as @paper_language" do
        paper_language = PaperLanguage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaperLanguage.any_instance.stub(:save).and_return(false)
        put :update, {:id => paper_language.to_param, :paper_language => { "title" => "invalid value" }}, valid_session
        assigns(:paper_language).should eq(paper_language)
      end

      it "re-renders the 'edit' template" do
        paper_language = PaperLanguage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaperLanguage.any_instance.stub(:save).and_return(false)
        put :update, {:id => paper_language.to_param, :paper_language => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paper_language" do
      paper_language = PaperLanguage.create! valid_attributes
      expect {
        delete :destroy, {:id => paper_language.to_param}, valid_session
      }.to change(PaperLanguage, :count).by(-1)
    end

    it "redirects to the paper_languages list" do
      paper_language = PaperLanguage.create! valid_attributes
      delete :destroy, {:id => paper_language.to_param}, valid_session
      response.should redirect_to(paper_languages_url)
    end
  end

end
