require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaperTypesController do

  # This should return the minimal set of attributes required to create a valid
  # PaperType. As you add validations to PaperType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "title" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PaperTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paper_types as @paper_types" do
      paper_type = PaperType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paper_types).should eq([paper_type])
    end
  end

  describe "GET show" do
    it "assigns the requested paper_type as @paper_type" do
      paper_type = PaperType.create! valid_attributes
      get :show, {:id => paper_type.to_param}, valid_session
      assigns(:paper_type).should eq(paper_type)
    end
  end

  describe "GET new" do
    it "assigns a new paper_type as @paper_type" do
      get :new, {}, valid_session
      assigns(:paper_type).should be_a_new(PaperType)
    end
  end

  describe "GET edit" do
    it "assigns the requested paper_type as @paper_type" do
      paper_type = PaperType.create! valid_attributes
      get :edit, {:id => paper_type.to_param}, valid_session
      assigns(:paper_type).should eq(paper_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaperType" do
        expect {
          post :create, {:paper_type => valid_attributes}, valid_session
        }.to change(PaperType, :count).by(1)
      end

      it "assigns a newly created paper_type as @paper_type" do
        post :create, {:paper_type => valid_attributes}, valid_session
        assigns(:paper_type).should be_a(PaperType)
        assigns(:paper_type).should be_persisted
      end

      it "redirects to the created paper_type" do
        post :create, {:paper_type => valid_attributes}, valid_session
        response.should redirect_to(PaperType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved paper_type as @paper_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaperType.any_instance.stub(:save).and_return(false)
        post :create, {:paper_type => { "title" => "invalid value" }}, valid_session
        assigns(:paper_type).should be_a_new(PaperType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaperType.any_instance.stub(:save).and_return(false)
        post :create, {:paper_type => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested paper_type" do
        paper_type = PaperType.create! valid_attributes
        # Assuming there are no other paper_types in the database, this
        # specifies that the PaperType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaperType.any_instance.should_receive(:update_attributes).with({ "title" => "MyString" })
        put :update, {:id => paper_type.to_param, :paper_type => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested paper_type as @paper_type" do
        paper_type = PaperType.create! valid_attributes
        put :update, {:id => paper_type.to_param, :paper_type => valid_attributes}, valid_session
        assigns(:paper_type).should eq(paper_type)
      end

      it "redirects to the paper_type" do
        paper_type = PaperType.create! valid_attributes
        put :update, {:id => paper_type.to_param, :paper_type => valid_attributes}, valid_session
        response.should redirect_to(paper_type)
      end
    end

    describe "with invalid params" do
      it "assigns the paper_type as @paper_type" do
        paper_type = PaperType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaperType.any_instance.stub(:save).and_return(false)
        put :update, {:id => paper_type.to_param, :paper_type => { "title" => "invalid value" }}, valid_session
        assigns(:paper_type).should eq(paper_type)
      end

      it "re-renders the 'edit' template" do
        paper_type = PaperType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaperType.any_instance.stub(:save).and_return(false)
        put :update, {:id => paper_type.to_param, :paper_type => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested paper_type" do
      paper_type = PaperType.create! valid_attributes
      expect {
        delete :destroy, {:id => paper_type.to_param}, valid_session
      }.to change(PaperType, :count).by(-1)
    end

    it "redirects to the paper_types list" do
      paper_type = PaperType.create! valid_attributes
      delete :destroy, {:id => paper_type.to_param}, valid_session
      response.should redirect_to(paper_types_url)
    end
  end

end
